name: Twice Daily Inventory Sync

on:
  schedule:
    # 8:00 AM IST is 02:30 UTC
    # 4:00 PM IST is 10:30 UTC
    - cron: '30 1,10 * * *'
  workflow_dispatch: # This adds a "Run Now" button for testing

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pandas openpyxl pandas-gbq google-cloud-bigquery

      - name: Execute Python Script
        run: python main.py
